config/routes.rb
Rails.application.routes.draw do
  resources :articles

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    get "let_me_enter", to: "users/sessions#new"
  end

  resources :events

  resources :comments

  resources :alboms

  resources :masters

  resources :services

  get 'contacts' => 'services#contacts', :as => :contacts

  root 'services#home'

end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :photo, :styles => {:full => "600x600",:medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/services/:style/missing.png"
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show, :home, :contacts, :about]
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  def home
  end


  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :description, :photo)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
  def strip_tags str
    ActionController::Base.helpers.strip_tags(str)
  end
end

app/views/services/_form.html.haml
= form_for @service, :html => { :multipart => true } do |f|
  - if @service.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Название"
    = f.text_field :title
  .field
    = f.label "Описание"
    = f.text_area :description
  .field
    = f.label "Обложка"
    = f.file_field :photo
  .actions
    = f.submit 'Сохранить'

app/views/services/contacts.html.haml
%p#notice= notice
%h1
  Наши контакты

%p 
  По всем интересующим Вас вопросам звоните по тел.: 
  %br
    %b
      098-510-60-24
%p
  Найти нас можно по адресу:
  %br 
    %b
      ул. Южная 9/3

= "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2645.879730326776!2d35.049388499999985!3d48.4588371!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40dbe2d9358f9045%3A0x657f8730a0b37c12!2z0J_RltCy0LTQtdC90L3QsCDQstGD0LsuLCA5LCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC-0LLRgdGM0LosINCU0L3RltC_0YDQvtC_0LXRgtGA0L7QstGB0YzQutCwINC-0LHQu9Cw0YHRgtGMLCDQo9C60YDQsNC40L3QsA!5e0!3m2!1sru!2sru!4v1416821366463\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\"></iframe>".html_safe

app/views/services/edit.html.haml
%h1 Editing service

= render 'form'

= link_to 'Показать', @service, :class => "button "

= link_to 'К списку', services_path, :class => "button "

app/views/services/home.html.haml
%p#notice= notice

%h2{ :class=>"MsoNormal", :style=>"text-align: center;", :align=>"center"}
  %em
    %span{ :style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      Добро пожаловать на сайт клуба &laquo;АриАднА&raquo;!!!
%p{:class=>"MsoNormal", :style=>"text-align: justify;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif;"}
      %br
        %span{:style=>"background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Мы искренне надеемся, что информация на данном сайте заинтересует вас, и Вы захотите посетить наши занятия, тренинги и мастер-классы.
          %br
          %span{:style=>"background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
            В клубе &laquo;АриАднА&raquo; каждый сможет найти для себя что-то интересное и с пользой провести время. А наши мастера, тренеры и психологи всегда рады поделиться с Вами интересной информацией.
        %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif;"}
        %span{:style=>"background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      Вы можете посетить общий курс тренингов &laquo;Будь режиссёром своей судьбы&raquo;. 
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      Данная программа поможет Вам найти ответы на давно волнующие Вас вопросы:
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp;  мироустройство!!! Законы судьбы;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp; как влияют отношения между родителями на дальнейшую судьбу ребенка;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp;  почему многие пары не могут зачать ребенка;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp; что такое причинно-следственные связи;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp; как создать и сохранить гармоничные отношения с противоположным полом;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp; правильная постановка и достижение цели;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp;причина неуверенности в себе, и почему вы не можете реализоваться в жизни;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp;как грамотно распоряжаться деньгами, во всех сферах жизни;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      = "- &nbsp;и т.д.".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      &nbsp;&nbsp;&nbsp;&nbsp; В клубе Вы можете посетить различные мастер - классы по рукоделию. Научиться делать своими руками прекрасные сувениры и подарки для любимых, родных, друзей и т.д.
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %em
    %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
      Также у нас можно посетить различные тренинги (по сексологии, риторике, научиться работать со своим биополем, овладеть мастерством перевоплощения в домашних условиях), и воспользоваться услугами массажистов.
%p{:class=>"MsoNormal", :style=>"text-align: center;", :align=>"center"}
  ="&nbsp;".html_safe
%p{:class=>"MsoNormal", :style=>"text-align: justify; text-indent: 35.4pt;"}
  %span{:style=>"font-size: 14pt; line-height: 115%; font-family: Arial, sans-serif; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"}
    %em
      В клубе &laquo;АриАднА&raquo; регулярно проходят занятия по йоге!
%p{:class=>"MsoNormal", :style=>"text-align: justify;"}
  &nbsp;

app/views/services/index.html.haml
%h1 Услуги
- if user_signed_in?
  = link_to 'Новая услуга', new_service_path, :class => " button dark_grey"

.services
  - @services.each do |service|
    .service
      .service_img.mar_20 
        %a{:href => service_path(service)}
          %img{ :src => service.photo(:thumb)}
      .service_name.mar_20 
        %a{:href => service_path(service)}
          = service.title
      - if user_signed_in?
        .buttons
          = link_to 'Редактировать', edit_service_path(service), :class => " button dark_grey"
          = link_to 'Удалить', service, :method => :delete, :data => { :confirm => 'Вы уверены?' }, :class => "button dsgnmoo"
      .service_desc.mar_20 
        = strip_tags(service.description).html_safe[0..360].html_safe
        %a{:href => service_path(service)}
          = "..."

app/views/services/new.html.haml
%h1 Новая услуга

= render 'form'

= link_to 'К списку', services_path, :class => "button "

app/views/services/show.html.haml
%p#notice= notice
%p
  %img{ :src => @service.photo(:medium)}
%p
  %b Название:
  = @service.title
%p
  %b Описание:
  = @service.description.html_safe

- if user_signed_in?
  = link_to 'Изменить', edit_service_path(@service), :class => "button "
= link_to 'К списку', services_path, :class => "button "