config/routes.rb
Rails.application.routes.draw do
  resources :articles

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    get "let_me_enter", to: "users/sessions#new"
  end

  resources :events

  resources :comments

  resources :alboms

  resources :masters

  resources :services

  get 'contacts' => 'services#contacts', :as => :contacts

  root 'services#home'

end

app/models/albom.rb
class Albom < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
end

app/controllers/alboms_controller.rb
class AlbomsController < ApplicationController
  before_action :set_albom, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /alboms
  # GET /alboms.json
  def index
    @alboms = Albom.all
  end

  # GET /alboms/1
  # GET /alboms/1.json
  def show
  end

  # GET /alboms/new
  def new
    @albom = Albom.new
  end

  # GET /alboms/1/edit
  def edit
  end

  # POST /alboms
  # POST /alboms.json
  def create
    @albom = Albom.new(albom_params)

    respond_to do |format|
      if @albom.save
        if params[:images]
          params[:images].each { |image|
            @albom.pictures.create(image: image)
          }
        end
        format.html { redirect_to @albom, notice: 'Albom was successfully created.' }
        format.json { render :show, status: :created, location: @albom }
      else
        format.html { render :new }
        format.json { render json: @albom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alboms/1
  # PATCH/PUT /alboms/1.json
  def update
    respond_to do |format|
      if @albom.update(albom_params)
        format.html { redirect_to @albom, notice: 'Albom was successfully updated.' }
        format.json { render :show, status: :ok, location: @albom }
      else
        format.html { render :edit }
        format.json { render json: @albom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alboms/1
  # DELETE /alboms/1.json
  def destroy
    @albom.destroy
    respond_to do |format|
      format.html { redirect_to alboms_url, notice: 'Albom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_albom
      @albom = Albom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def albom_params
      params.require(:albom).permit(:title, :when)
    end
end

app/helpers/alboms_helper.rb
module AlbomsHelper
end

app/views/alboms/_form.html.haml
= form_for @albom, :html => {:multipart => true} do |f|
  - if @albom.errors.any?
    #error_explanation
      %h2= "#{pluralize(@albom.errors.count, "error")} prohibited this albom from being saved:"
      %ul
        - @albom.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Название"
    = f.text_field :title
  .field
    = f.label "Дата создания"
    = f.datetime_select :when
  .field
    = f.label "Фото"
    = file_field_tag "images[]", type: :file, multiple: true 
  .actions
    = f.submit 'Сохранить'

app/views/alboms/edit.html.haml
%h1 Editing albom

= render 'form'

= link_to 'К просмотру', @albom, :class => "buttons"
= link_to 'К списку', alboms_path, :class => "buttons"

app/views/alboms/index.html.haml
%h1 Фото галерея
- if user_signed_in?
  = link_to 'Новый альбом', new_albom_path

%table{:class => "list"}
  %tr
    %th Название
    %th Дата создания
    %th
    %th
    %th

  - @alboms.each do |albom|
    %tr
      %td
        %a{:href => albom_path(albom) }
          = albom.title
      %td= albom.when.strftime("%d-%m-%Y %H:%M")
      - if user_signed_in?
        %td= link_to 'Редактировать', edit_albom_path(albom), :class => "button dark_grey"
        %td= link_to 'Удалить', albom, :method => :delete, :data => { :confirm => 'Уверены?' }, :class => "button dsgnmoo"

app/views/alboms/new.html.haml
%h1 Новый альбом

= render 'form'

= link_to 'К списку', alboms_path, :class => "button"

app/views/alboms/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @albom.title
%p
  %b When:
  = @albom.when.strftime("%d-%m-%Y %H:%M")

.gallery
  - @albom.pictures.each do |photo| 
    .my_pic
      = link_to image_tag(photo.image(:medium)),
                  photo.image(:full),
                  class: 'fancybox', rel: 'group',  alt: 'Photo' 
.buttons{:style => "clear:left"}
  = link_to 'Изменить', edit_albom_path(@albom),:class => "button"
  = link_to 'К списку', alboms_path,:class => "button"